---
title: "Exploratory Analysis SDO"
date: "2025-07-31"
output: html_document
---

Loading Packages

```{r}
library(deSolve)
```

Defining the SIR Model

```{r}
sir_model <- function(time, state, parameter){
  with(as.list(c(state, parameter)), {
    dS <- -beta * S * I/N # rate of change for sus
    dI <- beta * S * I/N - gamma * I #rocinfected
    dR <- gamma * I
    
    list(c(dS, dI, dR))
  })
}
```

Parameters 

```{r}
N <- 1000 #total pop
init <- c(S = 999, I = 1, R = 0) # initial state
parameters <- c(beta = 0.9, gamma = 0.05) # transmission rates
time <- seq(0, 160, by = 1) # time in days
```

Solve system using ode()

```{r}
output <- ode(y = init, times = time, func = sir_model, parms = parameters)
```

Output

```{r}
output <- as.data.frame(output)

matplot(output$time, output[,2:4], type = "l", lty = 1, lwd = 2,
        col = c("blue", "red", "green"), xlab = "Time (days)", ylab = "Population",
        main = "SIR Model Dynamics")
legend("right", legend = c("Susceptible", "Infected", "Recovered"),
       col = c("blue", "red", "green"), lty = 1, lwd = 2)

```
